---

global:
  checkNewVersion: true
  sendAnonymousUsage: false

providers:
  docker:
    endpoint: "tcp://dockersocketproxy:2375"
    exposedByDefault: false
    network: "traefik_proxy"
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

certificatesResolvers:
  httpresolver:
    acme:
      httpChallenge:
        entryPoint: web
      email: "<email>"
      storage: "/letsencrypt/acme.json"

api:
  dashboard: true
  insecure: false

log:
  level: "INFO"
